package:
  name: rapidjson
  version: 1.1.0

source:
  url: https://dev.opencascade.org/system/files/occt/3rdparty/rapidjson-1.1.0.zip
  sha256: 8e00c38829d6785a2dfb951bb87c6974fa07dfe488aa5b25deec4b8bc0f6a3ab

build:
  library: true
  script: |
    echo 'RapidJSON is self-contained and header-only.'
