package:
  name: ocp
  version: 7.5.3

source:
  path: /src/pyodide/packages/ocp-bindings/build/ocp/OCP/
  extras:
    - [setup.py, setup.py]

#requirements:
#  run:
#    - ocp-bindings

build:
  script: |
    rm FindOpenCascade.cmake
    rm CMakeLists.txt

    sed -i 's/off_type buf_sought;$/off_type buf_sought = 0;/' pystreambuf.h

    rm OpenGl*

    python -m pip install pybind11

    echo 'Patching pybind11...'
    sed \
      -i \
      's/static_assert(sizeof(IntType) <= sizeof(ssize_t), "Implicit narrowing is not permitted.");$//' \
      "$( python -c 'import pybind11 ; print(pybind11.get_include())' )"/pybind11/detail/common.h

    # TODO: Replace this since it might break anytime.
    sed -i '1115,+3d' Standard.cpp

    cp OCP.cpp OCP.txt
    cp Standard.cpp Standard.txt
    rm *.cpp
    cp OCP.txt OCP.cpp
    cp Standard.txt Standard.cpp


    ls -lah
