package:
  name: ocp
  version: 7.5.3

source:
  path: /src/pyodide/packages/ocp-bindings/build/ocp/OCP/
  extras:
    - [setup.py, setup.py]

#requirements:
#  run:
#    - ocp-bindings
#    - pybind11

build:
  cflags: -s SIDE_MODULE=1
  script: |
    rm FindOpenCascade.cmake
    rm CMakeLists.txt

    sed -i 's/off_type buf_sought;$/off_type buf_sought = 0;/' pystreambuf.h

    rm OpenGl*

    # TODO: Replace this since it might break anytime.
    sed -i '1115,+3d' Standard.cpp

    cp OCP.cpp OCP.txt
    cp Standard.cpp Standard.txt
    rm *.cpp
    cp OCP.txt OCP.cpp
    cp Standard.txt Standard.cpp

    # TODO: Remove this hack
    cp /src/pyodide/packages/ocp/setup.py .

    ls -lah
