package:
  name: occt-raw
  version: 7.6.1

source:
  url: https://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;sf=tgz;h=refs/tags/V7_6_1
  sha256: c111c635fa4cae05821640f5afbbf362efaee8dc51fcbee953866eec7482cd6a

build:
  library: true
