package:
  name: pybind11
  version: 2.9.1

source:
  url: https://github.com/pybind/pybind11/archive/refs/tags/v2.9.1.tar.gz
  sha256: c6160321dc98e6e1184cc791fbeadd2907bb4a0ce0e447f2ea4ff8ab56550913

build:
  library: true
  script: |
    # TODO: Remove this hack
    sed \
      -i \
      's/static_assert(sizeof(IntType) <= sizeof(ssize_t), "Implicit narrowing is not permitted.");$//' \
      "$( python -c 'import pybind11 ; print(pybind11.get_include())' )"/pybind11/detail/common.h
