package:
  name: occt
  version: 7.5.3

source:
  path: /src/pyodide/packages/occt-raw/build/occt-raw-7.5.3/

#requirements:
#  run:
#    - freetype

build:
  library: true
  script: |
    # TODO: There must be a better way...
    # Remove EM_ASM_
    sed -i '4667,+3d' src/OpenGl/OpenGl_Context.cxx

    # TODO: There must be a better way...
    FILE=src/OSD/OSD_MemInfo.cxx \
    && \
    cat \
      <( head -n 43 "${FILE}" ) \
      <( echo 'size_t OSD_MemInfo_getModuleHeapLength() { return 500000000; }' ) \
      <( tail -n +47 "${FILE}" ) \
    > "${FILE}.tmp" \
    && \
    mv "${FILE}.tmp" "${FILE}"

    # TODO: There must be a better way...
    # Remove EM_JS
    FILE=src/Message/Message_PrinterSystemLog.cxx \
    && \
    cat \
      <( head -n 57 "${FILE}" ) \
      <( \
        echo 'void occJSConsoleDebug(const char* theStr) {}' \
        && \
        echo 'void occJSConsoleInfo(const char* theStr) {}' \
        && \
        echo 'void occJSConsoleWarn(const char* theStr) {}' \
        && \
        echo 'void occJSConsoleError(const char* theStr) {}' \
      ) \
      <( tail -n +79 "${FILE}" ) \
    > "${FILE}.tmp" \
    && \
    mv "${FILE}.tmp" "${FILE}"

    mkdir ./build/
    emcmake cmake \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -D3RDPARTY_FREETYPE_DIR:PATH=${PYODIDE_ROOT}/packages/freetype/build/freetype-2.11.1/install/ \
      -DBUILD_MODULE_FoundationClasses:BOOL=ON \
      -DBUILD_MODULE_ModelingData:BOOL=ON \
      -DBUILD_MODULE_ModelingAlgorithms:BOOL=OFF \
      -DBUILD_MODULE_Visualization:BOOL=OFF \
      -DBUILD_MODULE_ApplicationFramework:BOOL=OFF \
      -DBUILD_MODULE_DataExchange:BOOL=OFF \
      -DBUILD_MODULE_Draw:BOOL=OFF \
      -DBUILD_LIBRARY_TYPE=Static \
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
      -DCMAKE_CXX_FLAGS='-s SIDE_MODULE=1' \
      -DCMAKE_INSTALL_PREFIX:PATH=$( pwd )/install/ \
      -S . \
      -B ./build/
    cd ./build/
    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
