package:
  name: ocp-bindings
  version: 7.5.3

source:
  url: https://github.com/CadQuery/OCP/archive/refs/tags/7.5.3.0.tar.gz
  sha256: 0bbbd895b5e955ba7639e09b696c4b0a1df3de4bbe5a60c981ef20f4ac00a030
  extract_dir: ocp
  extras:
    - [dump_symbols.py, dump_symbols.py]
    - [fix_configuration_file.py, fix_configuration_file.py]

#requirements:
#  run:
#    - occt
#    - rapidjson
#    - pybind11

build:
  library: true
  script: |
    rm -r opencascade/
    ln -s ${PYODIDE_ROOT}/packages/occt/build/occt-7.5.3/install/include/opencascade/ opencascade


    echo 'Dumping exported symbols...'
    rm symbols_mangled_*.dat
    nm --version
    python ./dump_symbols.py ${PYODIDE_ROOT}/packages/occt/build/occt-7.5.3/install/lib/
    ls -lah symbols_mangled_emscripten.dat


    git clone --depth 1 https://github.com/CadQuery/pywrap.git

    echo 'Removing progress bars...'
    sed \
      -i \
      's/tqdm(modules)/tqdm(modules, disable=True)/' \
      pywrap/bindgen/__init__.py
    sed \
      -i \
      's/tqdm(module_dict.items())/tqdm(module_dict.items(), disable=True)/' \
      pywrap/bindgen/__init__.py

    cd pywrap
    rm -r opencascade/
    rm symbols_mangled_*.dat ocp.toml FindOpenCascade.cmake
    python -m pip install -e .
    cd ..

    python -m pip show --verbose pywrap

    ls -lah ${HOME}/.local/bin/pywrap


    # https://cmake.org/cmake/help/v3.22/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html
    # https://github.com/Sarcasm/compdb


    echo 'Fixing configuration file...'
    python ./fix_configuration_file.py


    echo 'Generating bindings...'
    CONDA_PREFIX=${PYODIDE_ROOT}/packages/occt/build/occt-7.5.3/install/ \
      ${HOME}/.local/bin/pywrap \
      --verbose \
      --clean \
      --njobs ${PYODIDE_JOBS:-3} \
      --libclang /usr/lib/llvm-7/lib/libclang.so \
      --include /usr/lib/llvm-7/include/ \
      all \
      ocp.toml \
      Linux

    ls -lah ./OCP/
